stages:
  - format

format:
  stage: format
  image: node:latest   # Using a Node.js image that includes Yarn
  script:
    - echo "Installing project dependencies..."
    - yarn install     # Install project dependencies (including Prettier)
    - echo "Running Prettier to format code..."
    - yarn format      # Run Prettier using Yarn

    # Check if there are any changes after formatting
    - CHANGED_FILES=$(git status --porcelain)
    - |
     if [ -z "$CHANGED_FILES" ]; then
        echo "No changes were made by Prettier. Skipping commit.";
      else
        git config --global user.email "prettier@sharify.in"
        git config --global user.name "Prettier"
        git add .
        git commit -m "Auto-format code with Prettier [skip ci]"
        echo "$CI_COMMIT_REF_NAME"
        git push origin $CI_COMMIT_REF_NAME # Push changes to the branch
      fi
  only:
    - branches    # Run on all branches (default behavior for 'only' when not specified)
  except:
    - tags        # Exclude running on tags
